### ISSUE TITLE
Incompatible with Fabric API 0.60.0

### ISSUE THREAD

**Issue by Zekiu** [techno-sam/ServerMobs#7]
```
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'server_mobs'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.9.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.9-launcher.0.11.0.jar:0.11.0]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/object/builder/SpawnRestrictionAccessor
        at com.slimeist.server_mobs.entities.CrocodileEntity.registerSpawnRestrictions(CrocodileEntity.java:843) ~[server_mobs-1.0.3+1.19.2.jar:?]
        at com.slimeist.server_mobs.ServerMobsMod.onInitializeServer(ServerMobsMod.java:185) ~[server_mobs-1.0.3+1.19.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.object.builder.SpawnRestrictionAccessor
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.slimeist.server_mobs.entities.CrocodileEntity.registerSpawnRestrictions(CrocodileEntity.java:843) ~[server_mobs-1.0.3+1.19.2.jar:?]
        at com.slimeist.server_mobs.ServerMobsMod.onInitializeServer(ServerMobsMod.java:185) ~[server_mobs-1.0.3+1.19.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
        ... 8 more
```

Minecraft: 1.19.2
Fabric API: 0.60.0
Fabric Loader: 0.14.9
Server Mobs: 1.0.3

**Comment by techno-sam** [comment]
Should be fixed in 1.0.3, modrinth release soon
