### ISSUE TITLE
Crocodiles crash the server

### ISSUE THREAD

**Issue by CamperSamu** [techno-sam/ServerMobs#8]
```
[15:52:55] [Server thread/ERROR] (MinecraftServer) Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
at Not Enough Crashes deobfuscated stack trace.(1.19+build.1) ~[?:?]
at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:879) ~[server-intermediary.jar:?]
at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:289) ~[?:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.handler$cmk000$modifiedRunLoop(MinecraftServer:8885) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:644) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.slimeist.server_mobs.api.server_rendering.model.BakedServerEntityModel.createInstance(net.minecraft.class_1297)" because the return value of "com.slimeist.server_mobs.entities.CrocodileEntity.getBakedModel()" is null
at com.slimeist.server_mobs.entities.CrocodileEntity.createModelInstance(CrocodileEntity.java:287) ~[server_mobs-1.0.4+1.19.2.jar:?]
at com.slimeist.server_mobs.entities.CrocodileEntity.getModelInstance(CrocodileEntity.java:293) ~[server_mobs-1.0.4+1.19.2.jar:?]
at com.slimeist.server_mobs.entities.CrocodileEntity.tick(CrocodileEntity.java:220) ~[server_mobs-1.0.4+1.19.2.jar:?]
at net.minecraft.server.world.ServerWorld.redirect$boi000$servercore$shouldTickEntity(ServerWorld:6745) ~[?:?]
at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:712) ~[?:?]
at net.minecraft.world.World.tickEntity(World:466) ~[?:?]
at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:371) ~[?:?]
at net.minecraft.world.EntityList.forEach(EntityList:54) ~[?:?]
at net.minecraft.server.world.ServerWorld.tick(ServerWorld:339) ~[?:?]
at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:875) ~[server-intermediary.jar:?]
... 6 more
```

**Comment by techno-sam** [comment]
What other mods do you have?

**Comment by techno-sam** [comment]
You need to either have polymer-autohost active, or not present. I will add a config option to force-enable resource pack loading without that condition.

**Comment by techno-sam** [comment]
Try downloading latest ServerMobs (and API), and add
```json
{
  "force_rp_build": true
}
```
to a file called 'server_mobs_api.json' in your server's config directory. That will force it to build the resourcepack, which should fix your problems.

**Comment by CamperSamu** [comment]
oooh maybe it's the polymer version I have on my server (or my configs), will debug this later today as right now I don't have access to my PC

**Comment by CamperSamu** [comment]
Ok, now it works.
Thanks a lot!
